---
title: "Lab2"
author: "Agievets"
date: "2023-11-07"
output: html_document
---

```{r}
head(income_elec_state)
```
```{r}
dim(income_elec_state)
```
```{r}
k <- 10
```
```{r}
head(clustering)
```
```{r}
cluster_colors <- rainbow(k)
```
```{r}
clustering <- kmeans(income_elec_state, centers = k)
plot(income_elec_state, col = clustering$cluster)
points(clustering$centers, col = 1:k, pch = 8)
#plot(income_elec_state, col = cluster_colors[clustering$cluster], pch = 19, main = "Кластеризация k-средних")
#points(clustering$centers, col = cluster_colors, pch = 3, cex = 2)
#legend("topright", legend = 1:k, col = cluster_colors, pch = 3, title = "Кластер")
```
```{r}
wss <- numeric(15)
for (i in 1:15) wss[i] <- sum(kmeans(income_elec_state, centers=i)$withinss)
plot(1:15, wss, type="b", xlab="Number of Clusters", ylab="Within groups sum of squares")
```
```{r}
log10_data <- income_elec_state
log10_data$income <- log10(income_elec_state$income)
log10_data$elec <- log10(income_elec_state$elec)
#income_elec_state$income <- log10(income_elec_state$income)
#income_elec_state$elec <- log10(income_elec_state$elec)
#income_elec_state$income <- 10^(income_elec_state$income)
#income_elec_state$elec <- 10^(income_elec_state$elec)
#income_elec_state
```
#without log
```{r}
clustering <- kmeans(income_elec_state, centers = k)
wss <- numeric(15)
for (i in 1:15) wss[i] <- sum(kmeans(income_elec_state, centers=i)$withinss)
plot(1:15, wss, type="b", xlab="Number of Clusters", ylab="Within groups sum of squares")
```
#With log
```{r}
clustering <- kmeans(log10_data, centers = k)
wss <- numeric(15)
for (i in 1:15) wss[i] <- sum(kmeans(log10_data, centers=i)$withinss)
plot(1:15, wss, type="b", xlab="Number of Clusters", ylab="Within groups sum of squares")
```
```{r}
outliers <- income_elec_state[-which(rownames(income_elec_state) == "PR"),]
dim(outliers)
outliers$income <- log10(outliers$income)
outliers$elec <- log10(outliers$elec)
```
```{r}
clustering <- kmeans(outliers, centers = k)
wss <- numeric(15)
for (i in 1:15) wss[i] <- sum(kmeans(outliers, centers=i)$withinss)
plot(1:15, wss, type="b", xlab="Number of Clusters", ylab="Within groups sum of squares")
```
```{r}
library(maps)
map_order <- c('AL', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 
'GA', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 
'MD', 'MA', 'MA', 'MA', 'MI', 'MI', 'MN', 'MS', 'MO', 
'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NY', 'NY', 
'NY', 'NC', 'NC', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 
'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'VA', 
'VA', 'WA', 'WA', 'WA', 'WA', 'WA', 'WV', 'WI', 'WY')
map_color <- clustering$cluster[map_order]
map('state', col = map_color, fill=TRUE)
```
```{r}
dist_mat <- dist(income_elec_state, method = 'euclidean')
hclust_avg <- hclust(dist_mat, method = 'average')
clusters <- cutree(hclust_avg, k = 4)
plot(income_elec_state, col = clusters, main = "Average")
plot(hclust_avg)
rect.hclust(hclust_avg, k = 4, border = 1:4)
```
```{r}
dist_mat <- dist(income_elec_state, method = 'euclidean')
hclust_avg <- hclust(dist_mat, method = 'complete')
clusters <- cutree(hclust_avg, k = 4)
plot(income_elec_state, col = clusters, main = "Complete")
plot(hclust_avg)
rect.hclust(hclust_avg, k = 4, border = 1:4)
```
```{r}
dist_mat <- dist(income_elec_state, method = 'euclidean')
hclust_avg <- hclust(dist_mat, method = 'single')
clusters <- cutree(hclust_avg, k = 4)
plot(income_elec_state, col = clusters, main = "Single")
plot(hclust_avg)
rect.hclust(hclust_avg, k = 4, border = 1:4)
```
```{r}
dist_mat <- dist(income_elec_state, method = 'euclidean')
hclust_avg <- hclust(dist_mat, method = 'centroid')
clusters <- cutree(hclust_avg, k = 4)
plot(income_elec_state, col = clusters, main = "Centroid")
plot(hclust_avg)
rect.hclust(hclust_avg, k = 4, border = 1:4)
```
```{r}
dist_mat <- dist(log10_data, method = 'euclidean')
hclust_avg <- hclust(dist_mat, method = 'average')
clusters <- cutree(hclust_avg, k = 4)
plot(log10_data, col = clusters, main = "Average_log")
plot(hclust_avg)
rect.hclust(hclust_avg, k = 4, border = 1:4)
```
```{r}
dist_mat <- dist(log10_data, method = 'euclidean')
hclust_avg <- hclust(dist_mat, method = 'complete')
clusters <- cutree(hclust_avg, k = 4)
plot(log10_data, col = clusters, main = "Complete_log")
plot(hclust_avg)
rect.hclust(hclust_avg, k = 4, border = 1:4)
```
```{r}
dist_mat <- dist(log10_data, method = 'euclidean')
hclust_avg <- hclust(dist_mat, method = 'single')
clusters <- cutree(hclust_avg, k = 4)
plot(log10_data, col = clusters, main = "Single_log")
plot(hclust_avg)
rect.hclust(hclust_avg, k = 4, border = 1:4)
```
```{r}
dist_mat <- dist(log10_data, method = 'euclidean')
hclust_avg <- hclust(dist_mat, method = 'centroid')
clusters <- cutree(hclust_avg, k = 4)
plot(log10_data, col = clusters, main = "Centroid_log")
plot(hclust_avg)
rect.hclust(hclust_avg, k = 4, border = 1:4)
```
```{r}
dist_mat <- dist(outliers, method = 'euclidean')
hclust_avg <- hclust(dist_mat, method = 'average')
clusters <- cutree(hclust_avg, k = 4)
plot(log10_data, col = clusters, main = "Average_out")
plot(hclust_avg)
rect.hclust(hclust_avg, k = 4, border = 1:4)
```
```{r}
dist_mat <- dist(outliers, method = 'euclidean')
hclust_avg <- hclust(dist_mat, method = 'complete')
clusters <- cutree(hclust_avg, k = 4)
plot(log10_data, col = clusters, main = "Complete_out")
plot(hclust_avg)
rect.hclust(hclust_avg, k = 4, border = 1:4)
```

```{r}
dist_mat <- dist(outliers, method = 'euclidean')
hclust_avg <- hclust(dist_mat, method = 'single')
clusters <- cutree(hclust_avg, k = 4)
plot(log10_data, col = clusters, main = "Single_out")
plot(hclust_avg)
rect.hclust(hclust_avg, k = 4, border = 1:4)
```
```{r}
dist_mat <- dist(outliers, method = 'euclidean')
hclust_avg <- hclust(dist_mat, method = 'centroid')
clusters <- cutree(hclust_avg, k = 4)
plot(log10_data, col = clusters, main = "Centroid_out")
plot(hclust_avg)
rect.hclust(hclust_avg, k = 4, border = 1:4)
```

